
import { GoogleGenAI, Modality } from "@google/genai";

interface GenerateImageParams {
  imageDataUrl: string;
  prompt: string;
  format: string;
}

const getAiClient = () => {
  // We initialize the client inside the function to ensure we pick up 
  // the API_KEY from the environment at the moment of execution, 
  // specifically after the user has selected a key in the UI.
  if (!process.env.API_KEY) {
      throw new Error("API_KEY environment variable is not set");
  }
  return new GoogleGenAI({ apiKey: process.env.API_KEY });
};

/**
 * Analyzes the image using gemini-3-pro-preview to get a detailed description.
 */
export const analyzeImage = async (imageDataUrl: string): Promise<string> => {
  try {
    const ai = getAiClient();
    const parts = imageDataUrl.split(',');
    const mimeType = parts[0].match(/:(.*?);/)?.[1];
    const base64Data = parts[1];

    if (!mimeType) throw new Error("Invalid mime type");

    const response = await ai.models.generateContent({
      model: 'gemini-3-pro-preview',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: mimeType,
              data: base64Data
            }
          },
          {
            text: "Analyze this image in detail. Describe the subject, the lighting, the style, the colors, and the background environment. This description will be used to extend the image borders, so focus on visual continuity."
          }
        ]
      }
    });

    return response.text || "An image";
  } catch (error) {
    console.error("Error analyzing image:", error);
    return "";
  }
}

export const generateImage = async ({ imageDataUrl, prompt, format }: GenerateImageParams): Promise<string> => {
  try {
    const ai = getAiClient();
    const parts = imageDataUrl.split(',');
    if (parts.length !== 2) {
      throw new Error("Invalid data URL");
    }
    const mimeType = parts[0].match(/:(.*?);/)?.[1];
    const base64Data = parts[1];

    if (!mimeType) {
      throw new Error("Could not determine MIME type from data URL");
    }

    const supportedRatios = ['1:1', '3:4', '4:3', '9:16', '16:9'];
    const imageConfig: any = {
        imageSize: '2K', // Request high quality
    };

    // Only set aspectRatio if it's one of the supported values.
    // For unsupported ratios (like 2:3, 21:9), we rely on the input image dimensions 
    // and the model's ability to preserve context in image-to-image generation.
    if (supportedRatios.includes(format)) {
        imageConfig.aspectRatio = format;
    }

    const response = await ai.models.generateContent({
      model: 'gemini-3-pro-image-preview',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Data,
              mimeType: mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
        imageConfig: imageConfig,
      },
    });

    // The image generation model response structure
    const firstPart = response.candidates?.[0]?.content?.parts?.[0];
    
    // Check for inlineData (standard for smaller images/previews)
    if (firstPart && 'inlineData' in firstPart && firstPart.inlineData) {
      const { data, mimeType: responseMimeType } = firstPart.inlineData;
      return `data:${responseMimeType};base64,${data}`;
    }

    throw new Error("No image was generated by the API.");
  } catch (error) {
    console.error("Error generating image with Gemini API:", error);
    throw new Error("Failed to generate image. Please check the console for more details.");
  }
};
